version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    #command: sh -c "cd next-app && npm run build && npm run start"   
    command: sh -c "npm run dev"
    #command: sh -c "cd next-test && npm run test"
    ports:
      - "3000:3000"